# vi: ft=yaml
---
# heading-increment/header-increment - Heading levels should only increment by
# one level at a time
MD001: true

# first-heading-h1/first-header-h1 - First heading should be a top-level heading
MD002: false

# heading-style/header-style - Heading style
MD003: true

# ul-style - Unordered list style
MD004:
  style: asterisk

# list-indent - Inconsistent indentation for list items at the same level
MD005: true

# ul-start-left - Consider starting bulleted lists at the beginning of the line
MD006: true

# ul-indent - Unordered list indentation
MD007: true

# no-trailing-spaces - Trailing spaces
MD009: true

# no-hard-tabs - Hard tabs
MD010: true

# no-reversed-links - Reversed link syntax
MD011: false

# no-multiple-blanks - Multiple consecutive blank lines
MD012: false

# line-length - Line length
MD013: false

# commands-show-output - Dollar signs used before commands without showing
# output
MD014: false

# no-missing-space-atx - No space after hash on atx style heading
MD018: true

# no-multiple-space-atx - Multiple spaces after hash on atx style heading
MD019: false

# no-missing-space-closed-atx - No space inside hashes on closed atx style
# heading
MD020: false

# no-multiple-space-closed-atx - Multiple spaces inside hashes on closed atx
# style heading
MD021: false

# blanks-around-headings/blanks-around-headers - Headings should be surrounded
# by blank lines
MD022: false

# heading-start-left/header-start-left - Headings must start at the beginning
# of the line
MD023: true

# no-duplicate-heading/no-duplicate-header - Multiple headings with the same
# content
MD024: false

# single-title/single-h1 - Multiple top-level headings in the same document
MD025: false

# no-trailing-punctuation - Trailing punctuation in heading
MD026: false

# no-multiple-space-blockquote - Multiple spaces after blockquote symbol
MD027: false

# no-blanks-blockquote - Blank line inside blockquote
MD028: false

# ol-prefix - Ordered list item prefix
MD029: false

# list-marker-space - Spaces after list markers
MD030: false

# blanks-around-fences - Fenced code blocks should be surrounded by blank lines
MD031: false

# blanks-around-lists - Lists should be surrounded by blank lines
MD032: false

# no-inline-html - Inline HTML
MD033: false

# no-bare-urls - Bare URL used
MD034: false

# hr-style - Horizontal rule style
MD035: false

# no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a
# heading
MD036: false

# no-space-in-emphasis - Spaces inside emphasis markers
MD037: false

# no-space-in-code - Spaces inside code span elements
MD038: false

# no-space-in-links - Spaces inside link text
MD039: false

# fenced-code-language - Fenced code blocks should have a language specified
MD040: false

# first-line-heading/first-line-h1 - First line in a file should be a top-level
# heading
MD041: false

# no-empty-links - No empty links
MD042: false

# required-headings/required-headers - Required heading structure
MD043: false

# proper-names - Proper names should have the correct capitalization
MD044: false

# no-alt-text - Images should have alternate text (alt text)
MD045: false

# code-block-style - Code block style
MD046: false

# single-trailing-newline - Files should end with a single newline character
MD047: true

# code-fence-style - Code fence style
MD048: false
