acronyms:
  QTS: Qualified Teacher Status
  NQT: Newly Qualified Teacher
  DSA: Disabled Students’ Allowance
  EU: European Union
  EEA: European Economic Area
  DfE: Department for Education
  TLR: Teaching and learning responsibility
  SCITT: school-centred initial teacher training
  CAS: confirmation of acceptance for studies
  ICT: information and communication technologies
  NPQ: National Professional Qualification
  SKE: subject knowledge enhancement
  PGCE: postgraduate certificate of education
  BEd: Bachelor of Education degree
  BA: Bachelor of Arts
  Bsc: Bachelor of Science
  ITT: initial teacher training
  EYTS: Early Years Teacher Status
  EYITT: Early Years Initial Teacher Training
