redirects:
  # Guidance
  "/ways-to-train-guidance": "/guidance/become-a-teacher-in-england"
  "/train-to-become-a-teacher": "/guidance/become-a-teacher-in-england"
  "/guidance/train-to-become-a-teacher": "/guidance/become-a-teacher-in-england"

  "/finance-guidance": "/guidance/financial-support-for-teacher-training"
  "/financial-support-for-teacher-training": "/guidance/financial-support-for-teacher-training"

  "/guidance": "/guidance/become-a-teacher-in-england"

  # Top-level pages
  "/life-as-a-teacher/teachers-salaries-and-benefits": "/teachers-salaries-and-benefits"
  "/life-as-a-teacher/my-story-into-teaching": "/my-story-into-teaching"
  "/life-as-a-teacher": "/teaching-as-a-career"
  "/teachers-salaries-and-benefits": "/salaries-and-benefits"
  "/international-teachers": "/international-candidates"
  "/international-students": "/international-candidates"

  # Campaign landing pages
  "/helping-you-become-a-teacher": "/three-things-to-help-you-get-into-teaching"

  # Story lists
  "/life-as-a-teacher/my-story-into-teaching/career-changers": "/my-story-into-teaching/career-changers"
  "/life-as-a-teacher/my-story-into-teaching/career-progression": "/my-story-into-teaching/career-progression"
  "/life-as-a-teacher/my-story-into-teaching/international-career-changers": "/my-story-into-teaching/international-career-changers"
  "/life-as-a-teacher/my-story-into-teaching/making-a-difference": "/my-story-into-teaching/making-a-difference"
  "/life-as-a-teacher/my-story-into-teaching/returners": "/my-story-into-teaching/returners"
  "/life-as-a-teacher/my-story-into-teaching/teacher-training-stories": "/my-story-into-teaching/teacher-training-stories"

  # Stories
  "/life-as-a-teacher/my-story-into-teaching/career-changers/becoming-a-mum-sparked-my-interest-in-teaching": "/my-story-into-teaching/career-changers/becoming-a-mum-sparked-my-interest-in-teaching"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/financiers-future-in-maths": "/my-story-into-teaching/career-changers/financiers-future-in-maths"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/from-construction-site-to-classroom": "/my-story-into-teaching/career-changers/from-construction-site-to-classroom"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/from-developing-software-to-developing-students": "/my-story-into-teaching/career-changers/from-developing-software-to-developing-students"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/leaping-to-head-of-department": "/my-story-into-teaching/career-changers/leaping-to-head-of-department"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/make-a-difference-to-young-people": "/my-story-into-teaching/career-changers/make-a-difference-to-young-people"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/natural-transition-from-engineering-to-teaching-physics": "/my-story-into-teaching/career-changers/natural-transition-from-engineering-to-teaching-physics"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/passing-on-my-knowledge": "/my-story-into-teaching/career-changers/passing-on-my-knowledge"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/police-officer-to-pe-teacher": "/my-story-into-teaching/career-changers/police-officer-to-pe-teacher"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/royal-marine-commando-to-geography-teacher": "/my-story-into-teaching/career-changers/royal-marine-commando-to-geography-teacher"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/school-experience-helped-me-decide-to-switch": "/my-story-into-teaching/career-changers/school-experience-helped-me-decide-to-switch"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/swapping-senior-management-for-students": "/my-story-into-teaching/career-changers/swapping-senior-management-for-students"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/teaching-gave-me-purpose": "/my-story-into-teaching/career-changers/teaching-gave-me-purpose"
  "/life-as-a-teacher/my-story-into-teaching/career-changers/transferring-my-skills-to-teaching": "/my-story-into-teaching/career-changers/transferring-my-skills-to-teaching"
  "/life-as-a-teacher/my-story-into-teaching/career-progression/grasp-every-opportunity": "/my-story-into-teaching/career-progression/grasp-every-opportunity"
  "/life-as-a-teacher/my-story-into-teaching/career-progression/lawyer-to-assistant-teacher": "/my-story-into-teaching/career-progression/lawyer-to-assistant-teacher"
  "/life-as-a-teacher/my-story-into-teaching/career-progression/leaping-to-head-of-department": "/my-story-into-teaching/career-progression/leaping-to-head-of-department"
  "/life-as-a-teacher/my-story-into-teaching/career-progression/newly-qualified-to-head-of-faculty": "/my-story-into-teaching/career-progression/newly-qualified-to-head-of-faculty"
  "/life-as-a-teacher/my-story-into-teaching/career-progression/nqt-to-head-of-biology": "/my-story-into-teaching/career-progression/nqt-to-head-of-biology"
  "/life-as-a-teacher/my-story-into-teaching/career-progression/one-year-from-post-grad-to-hod": "/my-story-into-teaching/career-progression/one-year-from-post-grad-to-hod"
  "/life-as-a-teacher/my-story-into-teaching/international-career-changers/returning-to-teaching-with-international-experience": "/my-story-into-teaching/international-career-changers/returning-to-teaching-with-international-experience"
  "/life-as-a-teacher/my-story-into-teaching/international-career-changers/returning-to-teaching-with-support-from-an-adviser": "/my-story-into-teaching/international-career-changers/returning-to-teaching-with-support-from-an-adviser"
  "/life-as-a-teacher/my-story-into-teaching/making-a-difference/broadening-horizons-through-travelling-and-teaching": "/my-story-into-teaching/making-a-difference/broadening-horizons-through-travelling-and-teaching"
  "/life-as-a-teacher/my-story-into-teaching/making-a-difference/getting-our-geek-on-kids-coding": "/my-story-into-teaching/making-a-difference/getting-our-geek-on-kids-coding"
  "/life-as-a-teacher/my-story-into-teaching/making-a-difference/going-back-and-giving-back": "/my-story-into-teaching/making-a-difference/going-back-and-giving-back"
  "/life-as-a-teacher/my-story-into-teaching/making-a-difference/inspiring-our-young-entrepreneurs": "/my-story-into-teaching/making-a-difference/inspiring-our-young-entrepreneurs"
  "/life-as-a-teacher/my-story-into-teaching/making-a-difference/no-two-days-are-the-same": "/my-story-into-teaching/making-a-difference/no-two-days-are-the-same"
  "/life-as-a-teacher/my-story-into-teaching/making-a-difference/turning-a-tough-lesson-into-success": "/my-story-into-teaching/making-a-difference/turning-a-tough-lesson-into-success"
  "/life-as-a-teacher/my-story-into-teaching/returners/getting-back-into-the-classroom": "/my-story-into-teaching/returners/getting-back-into-the-classroom"
  "/life-as-a-teacher/my-story-into-teaching/returners/top-tips-for-returning-teachers": "/my-story-into-teaching/returners/top-tips-for-returning-teachers"
  "/life-as-a-teacher/my-story-into-teaching/teacher-training-stories/banker-turned-teacher": "/my-story-into-teaching/teacher-training-stories/banker-turned-teacher"
  "/life-as-a-teacher/my-story-into-teaching/teacher-training-stories/salaried-teacher-training-classroom-learning": "/my-story-into-teaching/teacher-training-stories/salaried-teacher-training-classroom-learning"
  "/life-as-a-teacher/my-story-into-teaching/teacher-training-stories/teacher-training-its-worth-it": "/my-story-into-teaching/teacher-training-stories/teacher-training-its-worth-it"
  "/life-as-a-teacher/my-story-into-teaching/teacher-training-stories/why-dont-you-teach-miss": "/my-story-into-teaching/teacher-training-stories/why-dont-you-teach-miss"

  # slides
  "/slides": "/presentations"
